# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, restart the server process.

# Site settings
# If you look in the HTML files, you will see them accessed via
# {{ site.title }}, {{ site.email }}, and so on.
title: Backyard
tagline:
  en: Hair Salon in Bratislava
  sk: Kaderníctvo v Bratislave
description: 
  en: In the center of Rača, on the edge of the Little Carpathians, you’ll find the BackYard. The philosophy guiding our hairdressing container is to provide prompt, high-quality services in a welcoming, comfortable setting at reasonable prices.
  sk: BackYard sa nachádza na okraji časti Malých Karpát v srdci Rači. Toto miesto je iné ako ostatné lesklé a luxusné saloný. Filozofiou nášho malého kaderníckeho kontajnera je ziskať profesionálne služby za dostupné ceny v útulnom priateľskom prostredí ihned!

# Build settings
markdown: kramdown

#plugins:

permalink: pretty

# Access values inside YML files within the _text folder using
# {{{{ item.VALUE }}FILENAME}}
# For example, to call upon frontmatter within text/homepage
# {% for item in site.text.homepage %}
# {{ item.VALUE }} where VALUE is frontmatter wihin YML file
# or just {{site.text.homepage.VALUE }} (I THINK???)