- name:
  services: 
    - name: Wash & blow dry 
      tagline: Straight / wavy
      prices: 
        - 10
        - 15
        - 20
- name: Haircuts
  services: 
    - name: Undercut
      tagline: including wash & blow dry
      prices: 
        - 15
        - 20
        - 25
    - name: Refresh hair cut
      tagline: including wash & blow dry
      prices: 
        - 20
        - 25
        - 30
    - name: New cut
      tagline: including wash & blow dry
      prices: 
        - 20
        - 30
        - 35
    - name: Gentleman's haircut
      tagline: with clipper + wash
      prices: 
        - 15
- name: Curling
  services: 
    - name: as a separate service
      tagline: 
      prices: 
        - 25
    - name: after blow-drying
      tagline:
      prices: 
        - 15
- name: Straightening
  services: 
    - name: as a separate service
      tagline: 
      prices: 
        - 10
    - name: after blow-drying
      tagline:
      prices: 
        - 5
- name: Hair Dyeing
  services: 
    - name: Dyeing of roots
      tagline: including blow dry
      prices: 
        - from 45
    - name: Full hair dyeing
      tagline: including blow dry
      prices: 
        - 55
        - 65
        - 75
    - name: for each additional tube of dye
      tagline: if your hair and look require more than one
      prices: 
        - + 10
- name: Hair lightening / tinting / blow drying
  services: 
    - name: Simple lightening
      tagline: 
      prices: 
        - 60
        - 70
        - 80
    - name: baby highlights (bleaching of roots)
      tagline: 
      prices: 
        - from 70
    - name: ombré / balayage
      tagline: 
      prices: 
        - 90
        - 110
        - 130
    - name: full highlights
      tagline: 
      prices: 
        - 110
        - 140
        - 160
    - name: color change / bleaching
      tagline: 
      prices: 
        - 100
        - 160
        - 200
- name: Hair treatments
  services: 
    - name: Hair extensions and thickening 
      tagline: using the micro-ring method
      prices: 
      - Prices are approximate, and depend on the number of extensions and the density, material, and length of hair.