title:
  en: Services we offer
  sk: Naše služby
tagline:
  en: price list
  sk: cenník
services: 
  - id: Coloring / Farbenie
    title: 
      en: Coloring
      sk: Farbenie
    emoji: 🌈
    desc: 
      en: We color your hair with quality dyes
      sk: Farbenie vlasov kvalitnými farbami
    price: 
      en: from 30 €
      sk: od 30 €
  - id: Haircuts / Strihanie
    title: 
      en: Haircuts
      sk: Strihanie
    emoji: ✂️
    desc: 
      en: Haircuts for Ladies, Gentlemen and children
      sk: Strihanie pre Dámy, Pánov&nbsp;a&nbsp;deti
    price: 
      en: from 10 €
      sk: od 10 €
  - id: Blow drying / Fúkanie
    title: 
      en: Blow drying
      sk: Fúkanie
    emoji: 💨
    desc: 
      en: Blow drying for short or longh&nbsp;air
      sk: Fúkana krátkych či dlhých&nbsp;vlasov
    price: 
      en: from 15 €
      sk: od 15 €
  - id: Treatments / Vlasové kúry
    title: 
      en: Treatments
      sk: Vlasové kúry
    emoji: 💆‍♀️
    desc: 
      en: Professional hair care and hair&nbsp;regeneration
      sk: Profesionálna starostlivosť o vlasy a regenerácia vlasov
    price: 
      en: from 25 €
      sk: od 25 €
  - id: Extensions / Nadpájanie
    title: 
      en: Extensions
      sk: Nadpájanie
    emoji: 🎀
    desc: 
      en: with the Micro-Ring method
      sk: s Metódou Micro-Ring
    price: 
      en: Depends on length and material
      sk: Závisí od dĺžky a materiálu 