---
label: Services
hide_body: true
fields:
- type: field_group
  name: title
  label: Section Title
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: sk
    label: sk
- type: field_group
  name: tagline
  label: Section subtitle
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: sk
    label: sk
- type: field_group
  name: hair
  label: hair
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: sk
    label: sk
  hidden: true
- type: field_group
  name: hair-types
  label: Hair Types / Lengths
  fields:
  - type: list
    name: en
    label: en
  - type: list
    name: sk
    label: sk
- type: field_group_list
  name: categories
  label: Pricelist Categories
  fields:
  - type: text
    name: id
    label: ID (not visible)
    description: The ID is <strong>only</strong> visible in this editor, <strong>not</strong>
      the website.
  - type: field_group
    name: name
    label: Category Name
    fields:
    - type: text
      name: en
      label: en
    - type: text
      name: sk
      label: sk
  - type: field_group_list
    name: services
    label: Services
    fields:
    - type: text
      name: id
      label: ID (not visible)
      description: The ID is <strong>only</strong> visible in this editor, <strong>not</strong>
        the website.
    - type: field_group
      name: name
      label: Service Name
      fields:
      - type: text
        name: en
        label: en
      - type: text
        name: sk
        label: sk
    - type: field_group
      name: tagline
      label: Service description / subtitle
      fields:
      - type: text
        name: en
        label: en
      - type: text
        name: sk
        label: sk
    - type: list
      name: prices
      label: Prices
      description: "<strong>Add 1 price</strong> = same price, regardless of hair
        length<br><strong>Add 3 prices</strong> = 1 price for each hair length, in
        this order: short, medium, long"
- type: field_group
  name: disclaimer
  label: Disclaimer
  fields:
  - type: textarea
    name: en
    label: en
  - type: text
    name: sk
    label: sk
  description: This is a piece of text under the pricelist
pages:
- _data/services.yml
