---
label: Services
hide_body: true
fields:
- type: field_group
  name: title
  label: Section Title
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: sk
    label: sk
- type: field_group
  name: tagline
  label: Tagline (Script)
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: sk
    label: sk
- type: field_group
  name: hair
  label: hair
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: sk
    label: sk
  hidden: true
- type: field_group
  name: hair-types
  label: Hair Types
  fields:
  - type: list
    name: en
    label: en
  - type: list
    name: sk
    label: sk
- type: field_group
  name: categories
  label: Categories
  fields:
  - type: text
    name: name
    label: Category Name
  - type: field_group
    name: services
    label: Services under category
    fields:
    - type: field_group
      name: name
      label: Service Name
      fields:
      - type: text
        name: en
        label: en
      - type: text
        name: sk
        label: sk
    - type: field_group
      name: tagline
      label: Service tagline
      fields:
      - type: text
        name: en
        label: en
      - type: text
        name: sk
        label: sk
    - type: list
      name: prices
      label: Prices
      description: 'You can either list 1 price for all hair lengths, or 3 prices,
        one for each hair length, in this order: short, medium, long.'
- type: field_group
  name: disclaimer
  label: Disclaimer
  fields:
  - type: textarea
    name: en
    label: en
  - type: text
    name: sk
    label: sk
  description: This is what’s written underneath the price table.
